# This is a basic workflow to help you get started with Actions

name: 自动部署文档

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        npm-version: [9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
          run_install: true

      - name: 打包
        run: pnpm run build

      # 配置git用户名和邮箱
      - name: 配置git
        run: git config --global user.email "guojikun486546@163.com" && git config --global user.name "GuoJikun" && git config --global init.defaultBranch main

      - name: 部署文档到gh-pages
        env:
          BRANCH: gh-pages
          ACCESS_TOKEN: ${{ secrets.git_token }}
        run: cd ./src/.vitepress/dist && git init && git add -A && git commit -m "deploy" && git push -f https://$ACCESS_TOKEN@github.com/document-translate/stenciljs.git main:$BRANCH
